language: python
env:
  global:
    secure: BtBlaMXw1N7KgnNTapanGyLSurDtWzxk6OmQhX6eddif7MVd1wLJCqDeAMt4xoh3/szP51aplgqjOcSEkjAWTLefyGwB/MHuRjW3uopNOL8Zhd2scHlSaha3TtoJhMM5RLM+ufvoBLf4c4LYCLjdwrobsAbAsqdREhaKc3ETjAQ=
before_install:
- echo "local" > version
- cd src
install:
- pip install -e .
- pip install -r dev_requirements.txt
script:
- py.test --cov syncloud.owncloud